//ALL PHONES

const phones = {
  0: {
    brand: "Apple",
    name: "Iphone 12 Pro",
    memory: "512GB",
    cost: 1149,
    colors: ["gold", "silver", "gray"],
    ext: "Iphone12Pro.png",
  },
  1: {
    brand: "Apple",
    name: "Iphone SE 2020",
    memory: "64GB",
    cost: 349,
    colors: ["red", "white"],
    ext: "IphoneSE2020.png",
  },
  2: {
    brand: "Apple",
    name: "Iphone 13 mini",
    memory: "256GB",
    cost: 729,
    colors: ["blue", "white", "pink", "black"],
    ext: "Iphone13Mini.png",
  },
  3: {
    brand: "Google",
    name: "Pixel 6A",
    memory: "128GB",
    cost: 399,
    colors: ["white", "green", "black"],
    ext: "Pixel6A.png",
  },
  4: {
    brand: "Google",
    name: "Pixel 6 Pro",
    memory: "256GB",
    cost: 749,
    colors: ["black"],
    ext: "Pixel6Pro.png",
  },
  5: {
    brand: "Samsung",
    name: "Galaxy S22 Plus",
    memory: "128GB",
    cost: 949,
    colors: ["green", "black", "white", "pink"],
    ext: "GalaxyS22Plus.png",
  },
  6: {
    brand: "Samsung",
    name: "Galaxy A13",
    memory: "64GB",
    cost: 129,
    colors: ["black", "white"],
    ext: "GalaxyA13.png",
  },
  7: {
    brand: "Motorolla",
    name: "G82",
    memory: "128GB",
    cost: 249,
    colors: ["gray"],
    ext: "MotoG82.png",
  },
  8: {
    brand: "Motorolla",
    name: "Moto E30",
    memory: "32GB",
    cost: 89,
    colors: ["blue", "gray"],
    ext: "MotoE30.png",
  },
  9: {
    brand: "Nokia",
    name: "105",
    memory: "4MB",
    cost: 25,
    colors: ["black", "blue", "pink"],
    ext: "Nokia105.png",
  },
};

export { phones };
